FROM registry.access.redhat.com/ubi7/python-27

ENV OC_CLIENT_MIRROR https://mirror.openshift.com/pub/openshift-v3/clients/3.11.115/linux/oc.tar.gz
ENV UNINSTALL_PKGS "httpd24-httpd "
ENV INSTALL_PKGS "git vim python27-python-pip httpd-tools"
ENV WORK_DIR /infra-ansible
ENV HOME ${WORK_DIR}

USER root

WORKDIR ${WORK_DIR}

COPY . ${WORK_DIR}
COPY /root /

RUN yum -y remove $UNINSTALL_PKGS && \
    yum update -y && \
    yum search python | grep pip && \
    yum -y install --disableplugin=subscription-manager $INSTALL_PKGS && \
    curl $OC_CLIENT_MIRROR | tar -C /usr/local/bin/ -xzf - && \
    yum --disableplugin=subscription-manager clean all && \
    rm -rf /var/cache/yum && \
    mkdir -pv /etc/ansible && \
    echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts && \
    chmod g+w /etc/passwd && \
    bash -c "pip install -r requirements.txt"

USER ${USER_UID}

ENTRYPOINT ["/usr/local/bin/run"]
CMD ["sleep", "infinity"]
